### ISSUE TITLE
ERROR "- Looking for a ref that matches 'master' on the remote side." even if defined brach main

### ISSUE THREAD

**Issue by schirrel** [onekiloparsec/heroku-node-deploy-subfolder#2]
I'm getting the following error
```
error: The destination you provided is not a full refname (i.e.,
starting with "refs/"). We tried to guess what you meant by:

- Looking for a ref that matches 'master' on the remote side.
- Checking if the <src> being pushed ('fc9eddfc1b23c088101d1a19fd36fcd61bd4ce55')
  is a ref in "refs/{heads,tags}/". If so we add a corresponding
  refs/{heads,tags}/ prefix on the remote side.

Neither worked, so we gave up. You must fully qualify the ref.
hint: The <src> part of the refspec is a commit object.
hint: Did you mean to create a new branch by pushing to
hint: 'fc9eddfc1b23c088101d1a19fd36fcd61bd4ce55:refs/heads/master'?
error: failed to push some refs to 'https://git.heroku.com/schirrel-my-movies.git'
```

my configuration is:

```
 - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.0.4
      with:
        api_key: ${{secrets.HEROKU_API_KEY}}
        email: ${{secrets.HEROKU_EMAIL}}
        app_name: "schirrel-my-movies"
        branch: "main"
        subfolder: "dist"
```

i defined branch main, but seems that is not respecting and searching for the branch master
as can be seen in
https://github.com/schirrel/my-movies/actions/runs/425109647
